name: Node Github CI

on:
  push:
    branches:
      - main

jobs:
  # test:
  #   needs: deploy
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       node-version: [8.x, 10.x, 12.x]
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Use Node.js ${{ matrix.node-version }}
  #     uses: actions/setup-node@v1
  #     with:
  #       node-version: ${{ matrix.node-version }}
  #   - name: npm install and test
  #     run: |
  #       npm install
  #       npm test
  #     env:
  #       CI: true

  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: SSH and deploy node app
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          mkdir ~/containers 
          cd ~/containers
          git clone https://github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}.git
          cd ${{ github.event.repository.name }}
          git pull origin ${{github.ref_name}}
          [ ! -f .env ] && ~/containers/set_incremental_port.sh # Cria o .env usando como modelo o que está no servidor
          docker-compose down --rmi all
          docker-compose up -d --no-deps --build
